#ifndef OPCODES_H
#define OPCODES_H

#include <stdint.h>
#include "cpu.h"
#include "alu.h"

uint8_t decode(CPU *cpu, uint8_t opcode);
uint8_t decode_cb(CPU *cpu, uint8_t opcode);

uint8_t op_00(void);
uint8_t op_01(CPU *cpu);
uint8_t op_02(CPU *cpu);
uint8_t op_03(CPU *cpu);
uint8_t op_04(CPU *cpu);
uint8_t op_05(CPU *cpu);
uint8_t op_06(CPU *cpu);
uint8_t op_07(CPU *cpu);
uint8_t op_08(CPU *cpu);
uint8_t op_09(CPU *cpu);
uint8_t op_0a(CPU *cpu);
uint8_t op_0b(CPU *cpu);
uint8_t op_0c(CPU *cpu);
uint8_t op_0d(CPU *cpu);
uint8_t op_0e(CPU *cpu);
uint8_t op_0f(CPU *cpu);
uint8_t op_10(CPU *cpu);
uint8_t op_11(CPU *cpu);
uint8_t op_12(CPU *cpu);
uint8_t op_13(CPU *cpu);
uint8_t op_14(CPU *cpu);
uint8_t op_15(CPU *cpu);
uint8_t op_16(CPU *cpu);
uint8_t op_17(CPU *cpu);
uint8_t op_18(CPU *cpu);
uint8_t op_19(CPU *cpu);
uint8_t op_1a(CPU *cpu);
uint8_t op_1b(CPU *cpu);
uint8_t op_1c(CPU *cpu);
uint8_t op_1d(CPU *cpu);
uint8_t op_1e(CPU *cpu);
uint8_t op_1f(CPU *cpu);
uint8_t op_20(CPU *cpu);
uint8_t op_21(CPU *cpu);
uint8_t op_22(CPU *cpu);
uint8_t op_23(CPU *cpu);
uint8_t op_24(CPU *cpu);
uint8_t op_25(CPU *cpu);
uint8_t op_26(CPU *cpu);
uint8_t op_27(CPU *cpu);
uint8_t op_28(CPU *cpu);
uint8_t op_29(CPU *cpu);
uint8_t op_2a(CPU *cpu);
uint8_t op_2b(CPU *cpu);
uint8_t op_2c(CPU *cpu);
uint8_t op_2d(CPU *cpu);
uint8_t op_2e(CPU *cpu);
uint8_t op_2f(CPU *cpu);
uint8_t op_30(CPU *cpu);
uint8_t op_31(CPU *cpu);
uint8_t op_32(CPU *cpu);
uint8_t op_33(CPU *cpu);
uint8_t op_34(CPU *cpu);
uint8_t op_35(CPU *cpu);
uint8_t op_36(CPU *cpu);
uint8_t op_37(CPU *cpu);
uint8_t op_38(CPU *cpu);
uint8_t op_39(CPU *cpu);
uint8_t op_3a(CPU *cpu);
uint8_t op_3b(CPU *cpu);
uint8_t op_3c(CPU *cpu);
uint8_t op_3d(CPU *cpu);
uint8_t op_3e(CPU *cpu);
uint8_t op_3f(CPU *cpu);
uint8_t op_76(CPU *cpu);
uint8_t op_40_to_7f(CPU *cpu, uint8_t opcode);
uint8_t op_80_to_bf(CPU *cpu, uint8_t opcode);
uint8_t op_c0(CPU *cpu);
uint8_t op_c1(CPU *cpu);
uint8_t op_c2(CPU *cpu);
uint8_t op_c3(CPU *cpu);
uint8_t op_c4(CPU *cpu);
uint8_t op_c5(CPU *cpu);
uint8_t op_c6(CPU *cpu);
uint8_t op_c7(CPU *cpu);
uint8_t op_c8(CPU *cpu);
uint8_t op_c9(CPU *cpu);
uint8_t op_ca(CPU *cpu);
uint8_t op_cb(CPU *cpu);
uint8_t op_cc(CPU *cpu);
uint8_t op_cd(CPU *cpu);
uint8_t op_ce(CPU *cpu);
uint8_t op_cf(CPU *cpu);
uint8_t op_d0(CPU *cpu);
uint8_t op_d1(CPU *cpu);
uint8_t op_d2(CPU *cpu);
uint8_t op_d4(CPU *cpu);
uint8_t op_d5(CPU *cpu);
uint8_t op_d6(CPU *cpu);
uint8_t op_d7(CPU *cpu);
uint8_t op_d8(CPU *cpu);
uint8_t op_d9(CPU *cpu);
uint8_t op_da(CPU *cpu);
uint8_t op_dc(CPU *cpu);
uint8_t op_de(CPU *cpu);
uint8_t op_df(CPU *cpu);
uint8_t op_e0(CPU *cpu);
uint8_t op_e1(CPU *cpu);
uint8_t op_e2(CPU *cpu);
uint8_t op_e5(CPU *cpu);
uint8_t op_e6(CPU *cpu);
uint8_t op_e7(CPU *cpu);
uint8_t op_e8(CPU *cpu);
uint8_t op_e9(CPU *cpu);
uint8_t op_ea(CPU *cpu);
uint8_t op_ee(CPU *cpu);
uint8_t op_ef(CPU *cpu);
uint8_t op_f0(CPU *cpu);
uint8_t op_f1(CPU *cpu);
uint8_t op_f2(CPU *cpu);
uint8_t op_f3(CPU *cpu);
uint8_t op_f5(CPU *cpu);
uint8_t op_f6(CPU *cpu);
uint8_t op_f7(CPU *cpu);
uint8_t op_f8(CPU *cpu);
uint8_t op_f9(CPU *cpu);
uint8_t op_fa(CPU *cpu);
uint8_t op_fb(CPU *cpu);
uint8_t op_fe(CPU *cpu);
uint8_t op_ff(CPU *cpu);

// CB related
void rlc(CPU *cpu, uint8_t *ptr);
void rrc(CPU *cpu, uint8_t *ptr);
void rl(CPU *cpu, uint8_t *ptr);
void rr(CPU *cpu, uint8_t *ptr);
void sla(CPU *cpu, uint8_t *ptr);
void sra(CPU *cpu, uint8_t *ptr);
void swap(CPU *cpu, uint8_t *ptr);
void srl(CPU *cpu, uint8_t *ptr);

void rlc_hl(CPU *cpu, uint16_t hl);
void rrc_hl(CPU *cpu, uint16_t hl);
void rl_hl(CPU *cpu, uint16_t hl);
void rr_hl(CPU *cpu, uint16_t hl);
void sla_hl(CPU *cpu, uint16_t hl);
void sra_hl(CPU *cpu, uint16_t hl);
void swap_hl(CPU *cpu, uint16_t hl);
void srl_hl(CPU *cpu, uint16_t hl);

#endif